[package]
name = "irdest-jni"
description = "Irdest library for android"
version = "0.0.1"
edition = "2021"

[profile.release]
opt-level = "z" 
lto = true
codegen-units = 1

[lib]
name = "ratman_android"
crate-type = ["dylib"]

[dependencies]
ratmand = { version = "0.5.0", path = "../../../ratman", default-features = false }
async-std = { version = "1.0", features = ["attributes"] }
jni = { version = "0.19.0", default-features = false }
log = "0.4"
android_logger = "0.11"

[dependencies.netmod-mem]
path = "../../../netmods/netmod-mem"
