[package]
name = "cchamt"
version = "0.1.0"
authors = ["chichunchen <chichunchen844@gmail.com>", "Wang, Shaojie <swang115@ur.rochester.edu>"]

[dependencies]
chashmap = "2.2.0"
libc = "0.2.40"
rand = "0.4.2"
rayon = "1.0.1"

[lib]
name = "cchamt"
path = "src/lib.rs"
