[package]
name = "eris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.10"
chacha20 = "0.9"
thiserror = "1.0"
async-trait = "0.1"

[dev-dependencies]
async-std = { version = "1.10", features = [ "attributes" ] }
base32 = "0.4"
