# SPDX-FileCopyrightText: 2018-2022 Katharina Fey <kookie@spacekookie.de>
#
# SPDX-License-Identifier: CC0-1.0

[workspace]
members = [
    # The decentralised router
    "ratman",
    "ratman/lib-client",
    "ratman/lib-types",
    "ratman/lib-netmod",

    # Various utility crates
    "utils/task-notify",
    "utils/clockctrl",
    "utils/tracing-syslog",
    "utils/installer",

    # Available netmod drivers
    "netmods/netmod-mem",
    "netmods/netmod-inet",
    "netmods/netmod-lan",
    "netmods/netmod-wd",
    "netmods/netmod-fuzz",

    # End-user applications
    "clients/irdest-echo",
    "clients/irdest-proxy",
]
