# SPDX-FileCopyrightText: 2022 Yureka Lilian <yuka@yuka.dev>
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "async-eris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.10"
chacha20 = "0.9"
thiserror = "1.0"
async-trait = "0.1"
base32 = "0.4"
futures-lite = "1.12"
derive_more = "0.99"

[dev-dependencies]
async-std = { version = "1.10", features = [ "attributes" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.7"