[package]
name = "tracing-android"
version = "0.1.0"
authors = ["Jess 3Jane <me@jess.coffee>"]
edition = "2018"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-core = "0.1"
serde_json = "1.0"

[target.'cfg(target_os = "android")'.dependencies]
android_log-sys = "0.1"
