[package]
name = "useful-netmod-bits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netmod = { version ="0.5.0", path = "../../ratman/lib-netmod", package = "ratman-netmod" }

async-std = "1.0"
serde = "1.0"
bincode = "1.0"
