[package]
name = "useful-netmod-bits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libratman = { version = "0.5", path = "../../ratman/libratman", features = ["netmod"], package = "ratman" }

async-std = "1.0"
serde = "1.0"
bincode = "1.0"
