# SPDX-FileCopyrightText: 2022 Manos Pitsidianakis <manos@pitsidianak.is>
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "journal"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
cchamt = { "version" = "0.1.0", "path" = "../cchamt" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
