# SPDX-FileCopyrightText: 2023 Katharina Fey <kookie@spacekookie.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-AppStore

[package]
name = "libratman"
description = "Ratman types, client, and interface library"
version = "0.5.0"
edition = "2021"
license = "GPL-3.0-or-later"

[features]
## TODO: figure out if it makes sense to disable one or both of these features by default
default = [ "client", "netmod" ]
netmod = [ ]
client = [ "proto" ]
proto = [ "protobuf", "protoc-rust" ]
metrics = [ "prometheus-client" ]
daemon = [ "nix" ]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

async-trait = "0.1"
async-std = { version = "1.0", features = ["attributes"] }
byteorder = "1.0"
cfg-if = "1.0"
chrono = { version = "0.4", features = ["serde"] }
protobuf = { version = "2.19", optional = true }
thiserror = "1.0"

tracing = "0.1"
tracing-subscriber = "0.2"

blake2 = "0.9.0"
hex = "0.4"
rand = "0.7"
regex = "1.0"
twox-hash = "1.5"

prometheus-client = { version = "0.16", optional = true }
nix = { version = "0.23", optional = true }

[dev-dependencies]
serde_json = "1.0"
bincode = "1.2"


[build-dependencies]
protoc-rust = { version = "2.19", optional = true }

[package.metadata.docs.rs]
no-default-features = true
