# SPDX-FileCopyrightText: 2023 Katharina Fey <kookie@spacekookie.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-AppStore

[package]
name = "libratman"
description = "Ratman types, client, and interface library"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[features]
default = ["proto"]
proto = ["protobuf", "protoc-rust"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }

async-trait = "0.1"
async-std = { version = "1.0", features = ["attributes"] }
byteorder = "1.0"
cfg-if = "1.0"
chrono = { version = "0.4", features = ["serde"] }
protobuf = { version = "2.19", optional = true }
thiserror = "1.0"

tracing = "0.1"
tracing-subscriber = "0.2"

blake2 = "0.9.0"
hex = "0.4"
rand = "0.7"
regex = "1.0"
twox-hash = "1.5"

prometheus-client = "0.16"

[dev-dependencies]
serde_json = "1.0"
bincode = "1.2"


[build-dependencies]
protoc-rust = { version = "2.19", optional = true }

[package.metadata.docs.rs]
no-default-features = true
