[package]
name = "irdest-firmware-util"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[features]
std = []

[dependencies]
libratman = { path = "../../ratman/libratman", version = "0.5", package = "ratman" }