[package]
name = "irdest-firmware-util"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[features]
std = []

[dependencies]
ratman-types = { path = "../../ratman/lib-types", version = "0.4" }